var res = {
    HelloWorlds_png : "res/HelloWorld.png",
    BALL_JPG : "res/ball.jpg",
    BALL2_JPG : "res/ball2.jpg",
    BALL3_JPG : "res/ball3.jpg",
	HelloWorld_png : "res/demo/HelloWorld.png",
	MainScene_json : "res/demo/MainScene.json",
	TEST_PLIST : "res/test.plist",
	TEST_PNG : "res/test.png",
	GROSSINI_PNG : "res/grossini-generic.plist",
	ARMATURE_JSON : "res/testAnimate/myAnimation.ExportJson",
	ARMATURE_PLIST : "res/testAnimate/animated-grossini.plist",
	ARMETURE_PNG : "res/testAnimate/animated-grossini.png",
	HERO_JSON : "res/hero/Hero.ExportJson",
	HERO_PLIST : "res/hero/Hero0.plist",
	HERO_BLOOD_PLIST : "res/hero/blood.plist",
	HERO_PNG : "res/hero/Hero0.png",
	FIREMAN_JSON : "res/fireman/Demon.ExportJson",
	FIREMAN_PLIST : "res/fireman/Demon0.plist",
	FIREMAN_PNG : "res/fireman/Demon0.png",
	PARALLAX_LAYER : "res/parallax/bgLayer.jpg",
	PARALLAX_LAYER2 : "res/parallax/bgLayer2.png",
	PARALLAX_LAYER3 : "res/parallax/bgLayer3.png",
	PARALLAX_LAYER4 : "res/parallax/bgLayer4.png",
	TILED_MAP : "res/tiledMap/map.tmx",
	TILED_MAP_PNG : "res/tiledMap/tile0.png",
	TILED_DESERT_PNG : "res/tiledMap/tmw_desert_spacing.png",
	BM0_PNG : "res/bmFont/bm_0.png",
	BM_FNT : "res/bmFont/bm.fnt",
	BM_FONT_PNG : "res/bmFont/font_0.png",
	BM_FONT_FNT : "res/bmFont/font.fnt",
	PARTICLE_FIRE : "res/particle/fire.png",
	PARTICLE_FIREWORK : "res/particle/firework.png",
	PARTICLE_PLIST : "res/particle/particle.plist",
	PARTICLE_SNOW : "res/particle/snow.png",
	PARTICLE_STAR : "res/particle/star.png",
	PARTICLE_TEXTURE : "res/particle/texture.png",
//	POP1_PNG : "res/lolipop/1.png",
//	POP2_PNG : "res/lolipop/2.png",
//	POP3_PNG : "res/lolipop/3.png",
//	POP4_PNG : "res/lolipop/4.png",
//	POP5_PNG : "res/lolipop/5.png",
//	POP_BG_PNG : "res/lolipop/bg.jpg",
};

var g_resources = [
	"res/lolipop/1.png",
	"res/lolipop/2.png",
	"res/lolipop/3.png",
	"res/lolipop/4.png",
	"res/lolipop/5.png",
	"res/lolipop/bg.jpg"
];
for (var i in res) {
    g_resources.push(res[i]);
}
